version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - cloud-sdk-{{ checksum "scripts/install-and-activate-google-cloud-sdk.sh" }}
      - run:
          name: Install and Activate Gcloud
          command: /bin/bash scripts/install-and-activate-google-cloud-sdk.sh
      - save_cache:
          key: cloud-sdk-{{ checksum "scripts/install-and-activate-google-cloud-sdk.sh" }}
          paths:
            - ~/google-cloud-sdk
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Running Tests
          command: yarn test
      - run:
          name: Deploy to GAE
          command: ${HOME}/google-cloud-sdk/bin/gcloud app deploy